'use strict';
const CandyAudio=(()=>{
 let context=null,master=null,effects=null,ambience=null,noiseBuffer=null,ambienceTimer=3;
 function ensure(){if(context)return context;const Ctor=window.AudioContext||window.webkitAudioContext;if(!Ctor)return null;try{context=new Ctor();master=context.createGain();effects=context.createGain();ambience=context.createGain();effects.connect(master);ambience.connect(master);master.connect(context.destination);const n=Math.floor(context.sampleRate*.35);noiseBuffer=context.createBuffer(1,n,context.sampleRate);const data=noiseBuffer.getChannelData(0),rng=CandyCore.createRng('candy-audio-noise');for(let i=0;i<n;i++)data[i]=rng()*2-1;sync();}catch(_){context=null;}return context;}
 function unlock(){const ctx=ensure();if(ctx&&ctx.state==='suspended')ctx.resume().catch(()=>{});}
 function sync(){if(!context)return;master.gain.value=Math.max(0,Math.min(1,game.settings.masterVolume));effects.gain.value=Math.max(0,Math.min(1,game.settings.effectsVolume));ambience.gain.value=Math.max(0,Math.min(1,game.settings.ambienceVolume));}
 function spatial(pos){if(!pos)return 1;const dx=pos.x-game.player.x,dy=pos.y-game.player.y,dz=pos.z-game.player.z;return Math.max(0,1-Math.sqrt(dx*dx+dy*dy+dz*dz)/24);}
 function tone(freq,duration,type,gain,pos,dest){if(!context||context.state!=='running')return;const now=context.currentTime,o=context.createOscillator(),a=context.createGain();o.type=type||'sine';o.frequency.setValueAtTime(freq,now);o.frequency.exponentialRampToValueAtTime(Math.max(30,freq*.72),now+duration);const level=(gain||.08)*spatial(pos);a.gain.setValueAtTime(.0001,now);a.gain.exponentialRampToValueAtTime(Math.max(.0001,level),now+.008);a.gain.exponentialRampToValueAtTime(.0001,now+duration);o.connect(a);a.connect(dest||effects);o.start(now);o.stop(now+duration+.02);}
 function noise(duration,freq,gain,pos,dest){if(!context||context.state!=='running'||!noiseBuffer)return;const now=context.currentTime,s=context.createBufferSource(),f=context.createBiquadFilter(),a=context.createGain();s.buffer=noiseBuffer;f.type='bandpass';f.frequency.value=freq;f.Q.value=.8;a.gain.setValueAtTime((gain||.05)*spatial(pos),now);a.gain.exponentialRampToValueAtTime(.0001,now+duration);s.connect(f);f.connect(a);a.connect(dest||effects);s.start(now);s.stop(now+duration);}
 function material(id){if(id===GLASS)return[1450,.035];if(id===WOOD||id===PLANKS||id===LOLLIPOP_STICK)return[360,.07];if(id===STONE||id===DARK_STONE||id===BEDROCK)return[170,.08];if(id===SAND||id===SUGAR_BLOCK||id===SNOW)return[920,.045];if(id===WATER)return[520,.04];return[610,.055];}
 function play(type,d={}){if(!context||context.state!=='running')return;const pos=d.position;if(type==='blockHit'||type==='blockBroken'||type==='blockPlaced'){const s=material(d.blockId);noise(type==='blockHit'?.055:.11,s[0],s[1]*(type==='blockBroken'?1.35:1),pos);if(type==='blockPlaced')tone(s[0]*.55,.07,'square',.025,pos);}else if(type==='footstep'){const s=material(d.blockId);noise(.065,s[0]*.8,s[1]*.52,pos);}else if(type==='toolSwing'){noise(.065,1050,.024,pos);tone(d.action==='attack'?190:240,.07,'triangle',.018,pos);}else if(type==='itemPickedUp'){tone(740,.08,'sine',.05);setTimeout(()=>tone(1040,.1,'sine',.04),45);}else if(type==='itemEaten'){tone(280,.08,'triangle',.05);noise(.09,900,.025);}else if(type==='itemCrafted'||type==='ovenSmelted'){tone(type==='ovenSmelted'?410:520,.07,'square',.035);setTimeout(()=>tone(type==='ovenSmelted'?620:780,.12,'triangle',.045),55);}else if(type==='questAdvanced'){tone(660,.1,'sine',.05);setTimeout(()=>tone(990,.18,'sine',.055),80);}else if(type==='tradeCompleted'){tone(440,.08,'triangle',.04);setTimeout(()=>tone(660,.13,'triangle',.05),70);}else if(type==='petTamed'||type==='animalBred'){tone(560,.09,'sine',.05,pos);setTimeout(()=>tone(840,.16,'sine',.05,pos),70);}else if(type==='playerSlept'){tone(330,.25,'sine',.025);setTimeout(()=>tone(495,.3,'sine',.02),160);}else if(type==='mechanismPowered'){tone(260+(d.blockId||0)%8*35,.08,'square',.025,pos);}else if(type==='playerDamaged'||type==='entityDamaged'){noise(.13,190,.09,pos);tone(110,.12,'sawtooth',.045,pos);}else if(type==='ui')tone(d.confirm?720:480,.055,'square',.025);}
 function update(dt){sync();ambienceTimer-=dt;if(ambienceTimer>0||!context||context.state!=='running')return;ambienceTimer=4+CandyCore.createRng('ambience',Math.floor(game.gameTime/4),getBiome(game.player.x,game.player.z))()*7;const w=game.weather.type;if(w==='sugar-snow')noise(.3,1800,.012,null,ambience);else if(w==='candy-storm'){noise(.45,240,.025,null,ambience);tone(75,.4,'sine',.018,null,ambience);}else if(w==='sprinkles')noise(.18,1250,.014,null,ambience);else tone(180+getBiome(game.player.x,game.player.z)*55,.35,'sine',.008,null,ambience);}
 for(const type of ['blockHit','blockBroken','blockPlaced','footstep','toolSwing','itemPickedUp','itemEaten','itemCrafted','ovenSmelted','questAdvanced','tradeCompleted','petTamed','animalBred','playerSlept','mechanismPowered','playerDamaged','entityDamaged','ui'])CandyEvents.on(type,d=>play(type,d));
 return{unlock,update,sync};
})();
