'use strict';
const CROP_MAX_STAGE=7;
function isCropBlock(id){return id===COOKIE_CROP||id===SUGAR_CANE_CROP||id===GUMMY_BUSH;}
function isHydratedSoil(x,y,z){for(let dz=-4;dz<=4;dz++)for(let dx=-4;dx<=4;dx++)for(let dy=-1;dy<=1;dy++)if(getBlock(x+dx,y+dy,z+dz)===WATER)return true;return false;}
function plantCrop(x,y,z,blockId){setBlock(x,y,z,blockId);const state=getBlockState(x,y,z,true);state.growth=0;state.hydrated=isHydratedSoil(x,y-1,z);game.dirtyChunks.add(chunkKey(x>>4,z>>4));CandyEvents.emit('cropPlanted',{blockId,position:{x,y,z}});scheduleSaveGame();}
function tryFarmingAction(target,item){if(!target||!item)return false;const above={x:target.x,y:target.y+1,z:target.z};if(item.id===ITEM_WAFER_HOE&&(target.block===GRASS||target.block===DIRT)){setBlock(target.x,target.y,target.z,FROSTING_SOIL);damageHeldTool(1);playViewAction('place',.3);CandyEvents.emit('soilTilled',{position:target});return true;}if(target.block===FROSTING_SOIL&&getBlock(above.x,above.y,above.z)===AIR){let crop=0;if(item.id===ITEM_COOKIE_SEEDS)crop=COOKIE_CROP;else if(item.id===ITEM_GUMMY_SEEDS)crop=GUMMY_BUSH;else if(item.id===CANDY_CANE&&isHydratedSoil(target.x,target.y,target.z))crop=SUGAR_CANE_CROP;if(crop){plantCrop(above.x,above.y,above.z,crop);if(!game.creativeMode)removeFromSlot(game.selectedSlot);updateHotbar();return true;}}if(isCropBlock(target.block)){const state=getBlockState(target.x,target.y,target.z,true);if((state.growth||0)>=CROP_MAX_STAGE){harvestCrop(target.x,target.y,target.z,target.block,false);return true;}}return false;}
function harvestCrop(x,y,z,blockId,breaking){const state=getBlockState(x,y,z,true),mature=(state.growth||0)>=CROP_MAX_STAGE;let drops=[];if(blockId===COOKIE_CROP)drops=mature?[{id:ITEM_FLOUR,count:2},{id:ITEM_COOKIE_SEEDS,count:2}]:[{id:ITEM_COOKIE_SEEDS,count:1}];else if(blockId===GUMMY_BUSH)drops=mature?[{id:ITEM_GUMMY_BERRIES,count:3},{id:ITEM_GUMMY_SEEDS,count:2}]:[{id:ITEM_GUMMY_SEEDS,count:1}];else drops=mature?[{id:CANDY_CANE,count:2}]:[{id:CANDY_CANE,count:1}];for(const drop of drops)spawnItemDrop(drop.id,drop.count,x+.5,y+.5,z+.5,{x:0,y:1.5,z:0});if(breaking)game.blockStates.delete(blockEntityKey(x,y,z));else{state.growth=0;state.hydrated=isHydratedSoil(x,y-1,z);game.dirtyChunks.add(chunkKey(x>>4,z>>4));}CandyEvents.emit('cropHarvested',{blockId,mature,position:{x,y,z}});scheduleSaveGame();}
function updateFarming(dt){if(dt<=0)return;game.farming.accumulator+=dt;let ticks=0;while(game.farming.accumulator>=2&&ticks++<4){game.farming.accumulator-=2;game.farming.tick++;let processed=0;for(const [key,state] of game.blockStates){if(processed++>800)break;const [x,y,z]=key.split(',').map(Number),block=getBlock(x,y,z);if(!isCropBlock(block))continue;state.hydrated=isHydratedSoil(x,y-1,z);const light=Math.max(getBlockLightAt(x,y,z),getSkyLightAt(x,y,z)*game.daylight),biome=getBiome(x,z);const factor=block===SUGAR_CANE_CROP&&biome===BIOME_BEACH?1.35:block===GUMMY_BUSH&&biome===BIOME_FOREST?1.25:1;if((state.growth||0)<CROP_MAX_STAGE&&CandyCore.shouldAdvanceCrop(game.worldSeed,x,y,z,game.farming.tick,state.hydrated,light,factor)){state.growth=(state.growth||0)+1;game.dirtyChunks.add(chunkKey(x>>4,z>>4));scheduleSaveGame();}}updateBreeding(2);}}
function startAnimalBreeding(mob){if(!mob||!isAnimalMob(mob.type)||mob.baby||(mob.breedCooldown||0)>0)return false;mob.loveTime=30;for(let i=0;i<6;i++)spawnParticle(mob.x,mob.y+1,mob.z,(hash2D(i,1)-.5),1,(hash2D(i,2)-.5),[1,.2,.5,1],1);return true;}
function updateBreeding(dt){for(const mob of game.mobs){mob.breedCooldown=Math.max(0,(mob.breedCooldown||0)-dt);mob.loveTime=Math.max(0,(mob.loveTime||0)-dt);if(mob.baby){mob.age=(mob.age||0)+dt;if(mob.age>300)mob.baby=false;}}for(const mob of game.mobs){if(!mob.loveTime||mob.breedCooldown>0||mob.baby)continue;const mate=game.mobs.find(other=>other!==mob&&other.type===mob.type&&other.loveTime>0&&!other.baby&&(other.breedCooldown||0)<=0&&((other.x-mob.x)**2+(other.z-mob.z)**2)<16);if(!mate)continue;const baby=spawnMob(mob.type,(mob.x+mate.x)/2,mob.y,(mob.z+mate.z)/2,true);if(baby){baby.age=0;mob.loveTime=mate.loveTime=0;mob.breedCooldown=mate.breedCooldown=180;CandyEvents.emit('animalBred',{type:mob.type,position:baby});}}}
