'use strict';
const MECHANISM_BUDGET=512,MECHANISM_DIRECTIONS=[[1,0,0],[-1,0,0],[0,0,1],[0,0,-1],[0,1,0],[0,-1,0]];
function mechanismNeighbors(x,y,z){return MECHANISM_DIRECTIONS.map(([dx,dy,dz])=>({x:x+dx,y:y+dy,z:z+dz}));}
function markMechanismVisual(x,z){game.dirtyChunks.add(chunkKey(Math.max(0,Math.min(WORLD_CX-1,x>>4)),Math.max(0,Math.min(WORLD_CZ-1,z>>4))));}
function setMechanismPower(x,y,z,powered){const block=getBlock(x,y,z),state=getBlockState(x,y,z,true),before=!!state.powered;state.powered=!!powered;if(before===state.powered)return;if(block===LOLLIPOP_LAMP){const lit=state.manualOn!==false||state.powered;updateLightSource(x,y,z,lit?LOLLIPOP_LAMP:AIR);}if(block===WAFER_DOOR)markMechanismVisual(x,z);if(block===NOTE_CANDY&&powered&&!before)CandyEvents.emit('ui',{confirm:true,note:state.note||0});if(powered)CandyEvents.emit('mechanismPowered',{blockId:block,position:{x,y,z}});markMechanismVisual(x,z);}
function updateMechanisms(dt){if(dt<=0)return;game.mechanism.accumulator+=dt;if(game.mechanism.accumulator<.1)return;game.mechanism.accumulator-=.1;game.mechanism.tick++;const sources=[];for(const [key,state] of game.blockStates){const [x,y,z]=key.split(',').map(Number),block=getBlock(x,y,z);if(block===JELLY_WIRE)state.powered=false;else if(block===SUGAR_SWITCH&&state.on)sources.push({x,y,z});else if(block===FROSTING_PLATE){const active=Math.abs(game.player.x-(x+.5))<.55&&Math.abs(game.player.z-(z+.5))<.55&&game.player.y>=y&&game.player.y<y+1.2;state.on=active;if(active)sources.push({x,y,z});}else if(block===DELAY_CANDY&&state.pulseTick&&state.pulseTick<=game.mechanism.tick){state.pulseTick=0;state.pulseUntil=game.mechanism.tick+2;}if(block===DELAY_CANDY&&state.pulseUntil>=game.mechanism.tick)sources.push({x,y,z});}
 const queue=[],visited=new Set();for(const source of sources)for(const next of mechanismNeighbors(source.x,source.y,source.z))queue.push(next);let processed=0;while(queue.length&&processed<MECHANISM_BUDGET){const pos=queue.shift(),key=blockEntityKey(pos.x,pos.y,pos.z);if(visited.has(key))continue;visited.add(key);processed++;const block=getBlock(pos.x,pos.y,pos.z);if(block===JELLY_WIRE){const state=getBlockState(pos.x,pos.y,pos.z,true);state.powered=true;markMechanismVisual(pos.x,pos.z);for(const next of mechanismNeighbors(pos.x,pos.y,pos.z))queue.push(next);}else if(block===DELAY_CANDY){const state=getBlockState(pos.x,pos.y,pos.z,true);if(!state.pulseTick&&!state.pulseUntil)state.pulseTick=game.mechanism.tick+Math.max(1,state.delay||4);}}
 for(const [key] of game.blockStates){const [x,y,z]=key.split(',').map(Number),block=getBlock(x,y,z);if(block!==LOLLIPOP_LAMP&&block!==WAFER_DOOR&&block!==NOTE_CANDY)continue;const powered=mechanismNeighbors(x,y,z).some(pos=>{const b=getBlock(pos.x,pos.y,pos.z),s=getBlockState(pos.x,pos.y,pos.z,false);return(b===JELLY_WIRE&&s?.powered)||(b===SUGAR_SWITCH&&s?.on)||(b===DELAY_CANDY&&s?.pulseUntil>=game.mechanism.tick);});setMechanismPower(x,y,z,powered);}game.mechanism.lastProcessed=processed;}
function initializeMechanismState(x,y,z,blockId){if(![JELLY_WIRE,SUGAR_SWITCH,FROSTING_PLATE,DELAY_CANDY,NOTE_CANDY,LOLLIPOP_LAMP,WAFER_DOOR].includes(blockId))return;const state=getBlockState(x,y,z,true);if(blockId===SUGAR_SWITCH)state.on=false;if(blockId===DELAY_CANDY)state.delay=4;if(blockId===LOLLIPOP_LAMP)state.manualOn=true;state.powered=false;}
function interactMechanism(target){const state=getBlockState(target.x,target.y,target.z,true);if(target.block===SUGAR_SWITCH){state.on=!state.on;CandyEvents.emit('ui',{confirm:state.on});scheduleSaveGame();return true;}if(target.block===LOLLIPOP_LAMP){state.manualOn=state.manualOn===false;const lit=state.manualOn||state.powered;updateLightSource(target.x,target.y,target.z,lit?LOLLIPOP_LAMP:AIR);scheduleSaveGame();return true;}if(target.block===NOTE_CANDY){state.note=((state.note||0)+1)%8;CandyEvents.emit('ui',{confirm:true,note:state.note});scheduleSaveGame();return true;}return false;}
