'use strict';

const OVEN_FUELS={ [WOOD]:12,[PLANKS]:8,[ITEM_STICK]:3,[CANDY_CANE]:6,[FROSTING_BROWN]:10 };
const OVEN_SMELT_TIME=5;

function blockEntityKey(x,y,z){return x+','+y+','+z;}
function getOvenRecipe(inputId){const recipe=SMELTING_RECIPES.find(entry=>entry.ingredients.length===1&&entry.ingredients[0].id===inputId);if(!recipe)return null;return{inputId,inputCount:recipe.ingredients[0].count,outputId:recipe.result.id,outputCount:recipe.result.count,smeltTime:OVEN_SMELT_TIME};}
function createOvenState(){return{type:'oven',input:null,fuel:null,output:null,burnTime:0,progress:0,lit:false,lastSimulationTime:Date.now()};}
function getOvenState(pos,create){if(!pos)return null;const key=blockEntityKey(pos.x,pos.y,pos.z);let state=game.blockEntities.get(key);if(!state&&create){state=createOvenState();game.blockEntities.set(key,state);}return state||null;}
function setOvenLit(pos,state,lit){if(state.lit===lit)return;state.lit=lit;updateLightSource(pos.x,pos.y,pos.z,lit?FURNACE:AIR);}
function simulateOven(pos,state,seconds){const recipe=getOvenRecipe(state.input?.id);const result=CandyCore.advanceOven(state,seconds,recipe,OVEN_FUELS,64);const wasLit=state.lit;Object.assign(state,result.state);if(wasLit!==state.lit)updateLightSource(pos.x,pos.y,pos.z,state.lit?FURNACE:AIR);if(result.completed){const payload={itemId:recipe.outputId,count:result.completed*recipe.outputCount,position:pos};CandyEvents.emit('itemCrafted',payload);CandyEvents.emit('ovenSmelted',payload);for(let i=0;i<4;i++)spawnParticle(pos.x+.5,pos.y+1,pos.z+.5,(hash2D(i,1)-.5)*.4,.8,(hash2D(i,2)-.5)*.4,[1,.55,.2,1],1);}return result;}
function updateOvens(dt){if(dt<=0)return;for(const [key,state] of game.blockEntities){if(state.type!=='oven')continue;const [x,y,z]=key.split(',').map(Number);if(getBlock(x,y,z)!==FURNACE)continue;simulateOven({x,y,z},state,dt);state.lastSimulationTime=Date.now();}if(game.furnaceOpen)renderOvenUI();}
function applyOvenOfflineProgress(pos,state){const now=Date.now(),elapsed=Math.max(0,Math.min(300,(now-(state.lastSimulationTime||now))/1000));if(elapsed>0)simulateOven(pos,state,elapsed);state.lastSimulationTime=now;}
function ovenSlotClick(kind,shift){const state=getOvenState(game.furnacePos,true);if(kind==='output'){if(!state.output)return;if(shift){const moved=CandyCore.transferBetween([state.output],game.inventory,0,getItemMaxStack);if(!moved.ok)return;state.output=moved.source[0];game.inventory=moved.destination;updateHotbar();}else if(!game.cursorStack){game.cursorStack=state.output;state.output=null;}else if(game.cursorStack.id===state.output.id&&game.cursorStack.count+state.output.count<=64){game.cursorStack.count+=state.output.count;state.output=null;}else return;}else{const existing=state[kind];if(!game.cursorStack&&existing){game.cursorStack=existing;state[kind]=null;}else if(game.cursorStack&&!existing){state[kind]=game.cursorStack;game.cursorStack=null;}else if(game.cursorStack&&existing&&game.cursorStack.id===existing.id&&existing.count<64){const move=Math.min(64-existing.count,game.cursorStack.count);existing.count+=move;game.cursorStack.count-=move;if(game.cursorStack.count<=0)game.cursorStack=null;}else if(game.cursorStack&&existing){state[kind]=game.cursorStack;game.cursorStack=existing;}}state.lastSimulationTime=Date.now();renderOvenUI();updateCursorStackUI();scheduleSaveGame();}
function renderOvenSlot(id,slot){const button=document.getElementById(id);if(!button)return;button.innerHTML='';if(slot){const icon=document.createElement('div');icon.className='slot-icon';setItemIcon(icon,slot.id);button.appendChild(icon);if(slot.count>1){const count=document.createElement('span');count.className='slot-count';count.textContent=slot.count;button.appendChild(count);}}}
function renderOvenUI(){if(!game.furnacePos)return;const state=getOvenState(game.furnacePos,true),recipe=getOvenRecipe(state.input?.id),pct=recipe?Math.min(1,state.progress/recipe.smeltTime):0;const signature=[state.input?.id,state.input?.count,state.fuel?.id,state.fuel?.count,state.output?.id,state.output?.count,Math.round(pct*100),state.lit].join(':');if(state._uiSignature===signature)return;state._uiSignature=signature;renderOvenSlot('oven-input',state.input);renderOvenSlot('oven-fuel',state.fuel);renderOvenSlot('oven-output',state.output);document.getElementById('oven-progress-fill').style.width=(pct*100)+'%';document.getElementById('oven-progress-label').textContent=state.lit?Math.round(pct*100)+'% baking':(recipe?'Needs fuel or output space':'Idle');}
function autofillOvenRecipe(recipe){const state=getOvenState(game.furnacePos,true);if(state.input)return false;const ingredient=recipe.ingredients[0];const transaction=CandyCore.transactInventory(game.inventory,{remove:[ingredient]},getItemMaxStack);if(!transaction.ok)return false;game.inventory=transaction.slots;state.input={id:ingredient.id,count:ingredient.count};updateHotbar();renderOvenUI();scheduleSaveGame();return true;}
function breakBlockEntity(x,y,z){const key=blockEntityKey(x,y,z),state=game.blockEntities.get(key);if(!state)return;for(const slot of [state.input,state.fuel,state.output])if(slot)spawnItemDrop(slot.id,slot.count,x+.5,y+.8,z+.5,{x:0,y:2,z:0});game.blockEntities.delete(key);updateLightSource(x,y,z,AIR);scheduleSaveGame();}
document.getElementById('oven-input').addEventListener('click',event=>ovenSlotClick('input',event.shiftKey));
document.getElementById('oven-fuel').addEventListener('click',event=>ovenSlotClick('fuel',event.shiftKey));
document.getElementById('oven-output').addEventListener('click',event=>ovenSlotClick('output',event.shiftKey));
