'use strict';
const CandyDB=(()=>{
    const PARTS=['blocks','blockEntities','blockStates','itemDrops','tamedPets','persistentEntities'];let openPromise=null;
    function open(){if(!('indexedDB'in window))return Promise.resolve(null);if(openPromise)return openPromise;openPromise=new Promise((resolve,reject)=>{const request=indexedDB.open('candy-world-saves',1);request.onupgradeneeded=()=>request.result.createObjectStore('checkpoints');request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});return openPromise;}
    async function getRecord(db,key){return new Promise(resolve=>{const request=db.transaction('checkpoints','readonly').objectStore('checkpoints').get(key);request.onsuccess=()=>resolve(request.result||null);request.onerror=()=>resolve(null);});}
    function parsePayload(payload){if(typeof payload!=='string')return null;try{const value=JSON.parse(payload);return value&&typeof value==='object'&&!Array.isArray(value)?value:null;}catch{return null;}}
    async function readGeneration(db,key,generation){if(!generation)return null;const legacy=await getRecord(db,key+':'+generation);if(parsePayload(legacy?.payload))return legacy.payload;const metaRecord=await getRecord(db,key+':'+generation+':meta');if(!metaRecord?.value||typeof metaRecord.value!=='object')return null;const document={...metaRecord.value};for(const part of PARTS){const record=await getRecord(db,key+':'+generation+':'+part);if(record&&Array.isArray(record.value))document[part]=record.value;}const payload=JSON.stringify(document);return parsePayload(payload)?payload:null;}
    async function read(key){const db=await open();if(!db)return null;const manifest=await getRecord(db,key+':manifest');if(!manifest)return null;for(const generation of [manifest.active,manifest.previous]){const payload=await readGeneration(db,key,generation);if(!payload)continue;if(generation!==manifest.active){document.documentElement.dataset.saveRecovery='previous-checkpoint';console.warn('Recovered Candy World from the previous complete checkpoint.');}return payload;}return null;}
    function deleteGeneration(store,key,generation){if(!generation)return;store.delete(key+':'+generation);store.delete(key+':'+generation+':meta');for(const part of PARTS)store.delete(key+':'+generation+':'+part);}
    async function write(key,payload){const document=parsePayload(payload);if(!document)throw new Error('Refusing malformed checkpoint');const db=await open();if(!db)return false;const current=await getRecord(db,key+':manifest'),generation=Date.now()+'-'+Math.floor(Math.random()*1e6),meta={...document};for(const part of PARTS)delete meta[part];return new Promise((resolve,reject)=>{const tx=db.transaction('checkpoints','readwrite'),store=tx.objectStore('checkpoints');store.put({value:meta,writtenAt:Date.now()},key+':'+generation+':meta');for(const part of PARTS)store.put({value:Array.isArray(document[part])?document[part]:[],writtenAt:Date.now()},key+':'+generation+':'+part);store.put({active:generation,previous:current?.active||null,format:2,writtenAt:Date.now()},key+':manifest');deleteGeneration(store,key,current?.previous);tx.oncomplete=()=>resolve(true);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error);});}
    async function remove(key){const db=await open();if(!db)return;const manifest=await getRecord(db,key+':manifest');return new Promise(resolve=>{const tx=db.transaction('checkpoints','readwrite'),store=tx.objectStore('checkpoints');for(const generation of [manifest?.active,manifest?.previous])deleteGeneration(store,key,generation);store.delete(key+':manifest');tx.oncomplete=()=>resolve();tx.onerror=()=>resolve();});}
    async function corruptActiveForAudit(key){const db=await open(),manifest=await getRecord(db,key+':manifest');if(!db||!manifest?.active)return false;return new Promise(resolve=>{const tx=db.transaction('checkpoints','readwrite');deleteGeneration(tx.objectStore('checkpoints'),key,manifest.active);tx.oncomplete=()=>{localStorage.removeItem(key);localStorage.removeItem(key+'-backup');resolve(true);};tx.onerror=()=>resolve(false);});}
    return{open,read,write,remove,corruptActiveForAudit};
})();
