'use strict';

const TUTORIAL_STEPS=[
 {title:'Look around',detail:'Click the world, then move the mouse to look.'},
 {title:'Take a stroll',detail:'Use W A S D to move through the candy world.'},
 {title:'Gather a block',detail:'Hold left click or R while aiming at a block.'},
 {title:'Place a block',detail:'Select a block, then right-click or press F.'},
 {title:'Open your pack',detail:'Press E to open inventory and crafting.'},
 {title:'Craft something',detail:'Use the recipe guide to make your first item.'},
 {title:'Make a friend',detail:'Offer a treat to an animal when you are ready.'}
];

function hasValidLocalSave(){try{const raw=localStorage.getItem(SAVE_KEY);if(!raw)return false;const parsed=JSON.parse(raw);return !!parsed&&typeof parsed==='object'&&(parsed.player||parsed.inventory||parsed.blocks);}catch(_){return false;}}
function persistGlobalSettings(){try{localStorage.setItem('candy-world-settings-v1',JSON.stringify({...game.settings,keyBindings:{...game.keyBindings},tutorial:game.tutorial}));}catch(_){} }
function applyLiveSettings(){document.documentElement.style.setProperty('--hud-scale',String(game.settings.hudScale));document.documentElement.classList.toggle('reduced-flashing',!game.settings.flashing);document.getElementById('hud').style.transform=`scale(${game.settings.hudScale})`;document.getElementById('hud').style.transformOrigin='center bottom';if(typeof setRenderScale==='function')setRenderScale(game.settings.renderScale);Object.assign(game.chunkStreaming,CandyCore.computeStreamingConfig(game.settings.viewDistance));CandyAudio.sync();persistGlobalSettings();}
function setMetaVisible(id,visible){const el=document.getElementById(id);el.style.display=visible?'flex':'none';el.setAttribute('aria-hidden',String(!visible));}
function openSettings(){document.exitPointerLock?.();setMetaVisible('settings-overlay',true);syncSettingsControls();document.querySelector('#settings-overlay button')?.focus();}
function closeSettings(){setMetaVisible('settings-overlay',false);if(game.worldStarted&&game.paused)setMetaVisible('pause-overlay',true);else setMetaVisible('title-screen',true);}
function syncSettingsControls(){for(const control of document.querySelectorAll('[data-setting]')){const key=control.dataset.setting;if(control.type==='checkbox')control.checked=key==='viewBob'?game.settings.viewBob>0:!!game.settings[key];else control.value=game.settings[key];}for(const control of document.querySelectorAll('[data-keybind]'))control.value=game.keyBindings[control.dataset.keybind];}
function openPauseMenu(){if(!game.worldLoaded)return;game.paused=true;clearInputState();setMetaVisible('pause-overlay',true);document.getElementById('resume-game').focus();}
function resumeGame(){setMetaVisible('pause-overlay',false);game.paused=false;requestGamePointerLock();}
async function startCandyWorld(newWorld){if(game.worldStarted)return;if(newWorld&&hasValidLocalSave()&&!window.confirm('Replace the selected Candy World? Export it first if you want to keep it.'))return;if(newWorld){localStorage.removeItem(SAVE_KEY);localStorage.removeItem(SAVE_BACKUP_KEY);game.worldMode=document.getElementById('new-world-mode').value;game.difficulty=game.worldMode==='cozy'?'gentle':game.worldMode==='creative'?'peaceful':'standard';game.worldSeed=(document.getElementById('new-world-seed').value.trim()||'candy-default').slice(0,48);game.worldName=(document.getElementById('new-world-name').value.trim()||'Candy World').slice(0,32);game.generatorVersion=2;game.tutorial={step:0,dismissed:false,movementTime:0};persistGlobalSettings();}game.worldStarted=true;game.paused=false;setMetaVisible('title-screen',false);document.getElementById('loading').style.display='flex';await loadWorld();}
function returnToTitle(){saveGameNow();window.location.reload();}
function advanceTutorialEvent(type){if(game.tutorial.dismissed)return;const expected=['look','move','blockBroken','blockPlaced','inventoryOpened','itemCrafted','petTamed'][game.tutorial.step];if(type===expected){game.tutorial.step++;persistGlobalSettings();renderTutorial();}}
function renderTutorial(){const card=document.getElementById('tutorial-card');if(game.tutorial.dismissed||game.tutorial.step>=TUTORIAL_STEPS.length||!game.worldLoaded){card.hidden=true;return;}const step=TUTORIAL_STEPS[game.tutorial.step];card.hidden=false;document.getElementById('tutorial-title').textContent=step.title;document.getElementById('tutorial-detail').textContent=step.detail;}
function updateTutorial(dt){if(!game.worldLoaded||game.paused)return;if(game.pointerLocked)advanceTutorialEvent('look');const moving=game.keys.KeyW||game.keys.KeyA||game.keys.KeyS||game.keys.KeyD;game.tutorial.movementTime=moving?game.tutorial.movementTime+dt:0;if(game.tutorial.movementTime>.7)advanceTutorialEvent('move');renderTutorial();}
function initializeTitleScreen(){const valid=hasValidLocalSave();const continueButton=document.getElementById('continue-world');continueButton.hidden=!valid;document.getElementById('save-summary').textContent=valid?'A valid Candy World save is ready.':'No existing world yet—start a new adventure.';const reportStartError=error=>{game.worldStarted=false;console.error('Candy world start failed',error);document.getElementById('loadtext').textContent='World loading failed. Return to the title screen and retry.';};continueButton.addEventListener('click',()=>startCandyWorld(false).catch(reportStartError));document.getElementById('new-world').addEventListener('click',()=>startCandyWorld(true).catch(reportStartError));for(const button of document.querySelectorAll('.open-settings'))button.addEventListener('click',()=>{setMetaVisible('title-screen',false);setMetaVisible('pause-overlay',false);openSettings();});document.getElementById('settings-close').addEventListener('click',closeSettings);document.getElementById('resume-game').addEventListener('click',resumeGame);document.getElementById('return-title').addEventListener('click',returnToTitle);document.getElementById('open-controls').addEventListener('click',()=>{setMetaVisible('pause-overlay',false);toggleControlsOverlay();});document.getElementById('tutorial-dismiss').addEventListener('click',()=>{game.tutorial.dismissed=true;persistGlobalSettings();renderTutorial();});for(const control of document.querySelectorAll('[data-setting]'))control.addEventListener('input',()=>{const key=control.dataset.setting;if(control.type==='checkbox')game.settings[key]=key==='viewBob'?(control.checked?1:0):control.checked;else game.settings[key]=Number(control.value);applyLiveSettings();});for(const control of document.querySelectorAll('[data-keybind]'))control.addEventListener('change',()=>{game.keyBindings[control.dataset.keybind]=control.value;persistGlobalSettings();});syncSettingsControls();applyLiveSettings();CandyEvents.on('blockBroken',()=>advanceTutorialEvent('blockBroken'));CandyEvents.on('blockPlaced',()=>advanceTutorialEvent('blockPlaced'));CandyEvents.on('itemCrafted',()=>advanceTutorialEvent('itemCrafted'));CandyEvents.on('petTamed',()=>advanceTutorialEvent('petTamed'));}
