'use strict';

function getBlockState(x,y,z,create){const key=blockEntityKey(x,y,z);let state=game.blockStates.get(key);if(!state&&create){state={facing:0,open:false,text:'',connections:0};game.blockStates.set(key,state);}return state||null;}
function facingFromYaw(yaw){return((Math.round((-yaw)/(Math.PI/2))%4)+4)%4;}
function initializePlacedBlockState(x,y,z,blockId){if(![CUPCAKE_CHEST,WAFER_DOOR,CANDY_FENCE,WAFER_LADDER,CANDY_SIGN,WAFER_SLAB,WAFER_STAIRS,MARSHMALLOW_BED,LOLLIPOP_LAMP,JELLY_WIRE,SUGAR_SWITCH,FROSTING_PLATE,DELAY_CANDY,NOTE_CANDY].includes(blockId))return;const state=getBlockState(x,y,z,true);state.facing=facingFromYaw(game.player.yaw);if(blockId===CUPCAKE_CHEST&&!game.blockEntities.has(blockEntityKey(x,y,z)))game.blockEntities.set(blockEntityKey(x,y,z),{type:'chest',slots:new Array(27).fill(null)});initializeMechanismState(x,y,z,blockId);updateFenceConnectionsAround(x,y,z);scheduleSaveGame();}
function updateFenceConnectionsAt(x,y,z){if(getBlock(x,y,z)!==CANDY_FENCE)return;let mask=0;[[0,0,-1,1],[1,0,0,2],[0,0,1,4],[-1,0,0,8]].forEach(([dx,dy,dz,bit])=>{const b=getBlock(x+dx,y+dy,z+dz);if(b===CANDY_FENCE||isSolid(b))mask|=bit;});getBlockState(x,y,z,true).connections=mask;game.dirtyChunks.add(chunkKey(x>>4,z>>4));}
function updateFenceConnectionsAround(x,y,z){updateFenceConnectionsAt(x,y,z);updateFenceConnectionsAt(x+1,y,z);updateFenceConnectionsAt(x-1,y,z);updateFenceConnectionsAt(x,y,z+1);updateFenceConnectionsAt(x,y,z-1);}
function thinFacingBox(facing,thickness=.125){return facing%2===0?[0,0,facing===0?1-thickness:0,1,1,facing===0?1:thickness]:[facing===1?0:1-thickness,0,0,facing===1?thickness:1,1,1];}
function getBlockRenderBoxes(block,x,y,z){const state=getBlockState(x,y,z,false),facing=((state?.facing||0)+((state?.open||state?.powered)&&block===WAFER_DOOR?1:0))%4;if(block===WAFER_DOOR)return[thinFacingBox(facing)];if(block===WAFER_LADDER)return[thinFacingBox(facing,.08)];if(block===CANDY_SIGN)return[[.43,0,.43,.57,.7,.57],[.12,.65,.42,.88,1,.58]];if(block===FROSTING_PLATE)return[[.08,0,.08,.92,.1,.92]];if(block===JELLY_WIRE)return[[.08,0,.08,.92,.06,.92]];if(block===SUGAR_SWITCH)return[[.32,0,.32,.68,.28,.68]];if(block===DELAY_CANDY)return[[.12,0,.12,.88,.18,.88]];if(block===WAFER_SLAB)return[[0,0,0,1,.5,1]];if(block===MARSHMALLOW_BED)return[[0,0,0,1,.5,1]];if(block===WAFER_STAIRS){const top=facing%2===0?[0,.5,facing===0?.5:0,1,1,facing===0?1:.5]:[facing===1?0:.5,.5,0,facing===1?.5:1,1,1];return[[0,0,0,1,.5,1],top];}if(block===CANDY_FENCE){const boxes=[[.35,0,.35,.65,1.5,.65]],mask=state?.connections||0;if(mask&1)boxes.push([.43,.35,0,.57,.85,.5]);if(mask&2)boxes.push([.5,.35,.43,1,.85,.57]);if(mask&4)boxes.push([.43,.35,.5,.57,.85,1]);if(mask&8)boxes.push([0,.35,.43,.5,.85,.57]);return boxes;}return null;}
function getBlockCollisionBoxes(block,x,y,z){const boxes=getBlockRenderBoxes(block,x,y,z);if(block===WAFER_LADDER||block===CANDY_SIGN||block===JELLY_WIRE||block===SUGAR_SWITCH||block===DELAY_CANDY)return[];return boxes|| (isSolid(block)?[[0,0,0,1,1,1]]:[]);}
function boxesOverlapAabb(aabb,x,y,z,boxes){return boxes.some(box=>aabb.x0<x+box[3]&&aabb.x1>x+box[0]&&aabb.y0<y+box[4]&&aabb.y1>y+box[1]&&aabb.z0<z+box[5]&&aabb.z1>z+box[2]);}
function getChestState(pos){const key=blockEntityKey(pos.x,pos.y,pos.z);let state=game.blockEntities.get(key);if(!state){state={type:'chest',slots:new Array(27).fill(null)};game.blockEntities.set(key,state);}return state;}
function openChest(pos){game.chestOpen=true;game.chestPos={...pos};const chest=getChestState(pos);CandyEvents.emit('chestOpened',{position:pos});if(chest.structure&&!chest.opened){chest.opened=true;CandyEvents.emit('structureLootOpened',{family:chest.structure,position:pos});}exitGamePointerLock();document.getElementById('chest-overlay').style.display='flex';renderChestUI();}
function closeChest(){if(game.cursorStack){if(!addItem(game.cursorStack.id,game.cursorStack.count))spawnItemDrop(game.cursorStack.id,game.cursorStack.count,game.player.x,game.player.y+1,game.player.z);game.cursorStack=null;}game.chestOpen=false;game.chestPos=null;document.getElementById('chest-overlay').style.display='none';updateCursorStackUI();requestGamePointerLock();}
function chestSlotClick(index,shift){const chest=getChestState(game.chestPos),slot=chest.slots[index];if(shift&&slot){const moved=CandyCore.transferBetween(chest.slots,game.inventory,index,getItemMaxStack);if(moved.ok){chest.slots=moved.source;game.inventory=moved.destination;updateHotbar();}}else if(!game.cursorStack&&slot){game.cursorStack=slot;chest.slots[index]=null;}else if(game.cursorStack&&!slot){chest.slots[index]=game.cursorStack;game.cursorStack=null;}else if(game.cursorStack&&slot&&slot.id===game.cursorStack.id){const max=getItemMaxStack(slot.id),move=Math.min(max-slot.count,game.cursorStack.count);slot.count+=move;game.cursorStack.count-=move;if(game.cursorStack.count<=0)game.cursorStack=null;}else if(game.cursorStack&&slot){chest.slots[index]=game.cursorStack;game.cursorStack=slot;}renderChestUI();updateCursorStackUI();scheduleSaveGame();}
function renderChestUI(){if(!game.chestPos)return;const grid=document.getElementById('chest-grid'),chest=getChestState(game.chestPos);grid.innerHTML='';for(let i=0;i<27;i++){const button=document.createElement('button');button.type='button';button.className='storage-slot';button.setAttribute('role','gridcell');button.setAttribute('aria-label','Chest slot '+(i+1));const slot=chest.slots[i];if(slot){const icon=document.createElement('div');icon.className='slot-icon';setItemIcon(icon,slot.id);button.appendChild(icon);if(slot.count>1){const count=document.createElement('span');count.className='slot-count';count.textContent=slot.count;button.appendChild(count);}}button.addEventListener('click',event=>chestSlotClick(i,event.shiftKey));grid.appendChild(button);}}
function interactUtilityBlock(target){const {x,y,z,block}=target;if(block===CUPCAKE_CHEST){openChest({x,y,z});return true;}if(block===WAFER_DOOR){const state=getBlockState(x,y,z,true);state.open=!state.open;game.dirtyChunks.add(chunkKey(x>>4,z>>4));CandyEvents.emit('ui',{confirm:state.open});scheduleSaveGame();return true;}if(block===CANDY_SIGN){const state=getBlockState(x,y,z,true),value=window.prompt('Candy sign text (40 characters):',state.text||'');if(value!==null){state.text=String(value).replace(/[<>]/g,'').trim().slice(0,40);scheduleSaveGame();}return true;}if(block===MARSHMALLOW_BED){game.spawnPoint={x:x+.5,y:y+1,z:z+.5};const t=game.dayTime/DAY_CYCLE_LENGTH;if(t>=.5&&t<.92){game.dayTime=DAY_CYCLE_LENGTH*.08;for(let i=game.mobs.length-1;i>=0;i--)if(game.mobs[i].type===MOB_WARDEN)game.mobs.splice(i,1);CandyEvents.emit('playerSlept',{position:{x,y,z}});showQuestNotification('You slept until a strawberry sunrise.');}else showQuestNotification('Spawn set! The bed is ready for nighttime.');scheduleSaveGame();return true;}return false;}
function breakUtilityBlock(x,y,z,blockId){const key=blockEntityKey(x,y,z),entity=game.blockEntities.get(key);if(entity?.type==='chest')for(const slot of entity.slots)if(slot)spawnItemDrop(slot.id,slot.count,x+.5,y+.8,z+.5);if(entity)game.blockEntities.delete(key);game.blockStates.delete(key);updateFenceConnectionsAround(x,y,z);scheduleSaveGame();}
document.getElementById('chest-close').addEventListener('click',closeChest);
